### ISSUE TITLE
FROM-Address should be changed to a no-reply address

### ISSUE THREAD

**Issue by albig** [slub/slub_forms#15]
Currently, the mails sent by slub_forms contains the sender email and sender name in email FROM header.

This leads to problems, if the receiving mailserver is checking for the DKIM record of the sender domain. This will fail in most cases and the spam score will be rised.

Example:

- From: "Sender Name" <sender@sender.name>
- Reply-To: sender@sender.name
- To: feedback@example.com

Should be changed to something like

- From: "Sender Name via Example Forms" <no-reply@example.com>
- Reply-To: sender@sender.name
- To: feedback@example.com

**Comment by chrode** [comment]
Fixed with https://github.com/slub/slub_forms/pull/19/commits/4e72dd563d06510fa6d1d41f9326520d62be46f0
